### ISSUE TITLE
Change track Color

### ISSUE THREAD

**Issue by rewdt** [kcotias/react-native-animated-progress#2]
Hello,

Please how do I change the track color of the progress bar? the backroundColor prop changes just the color of the progress Item.

**Comment by kcotias** [comment]
Hey @rewdt, sorry for the late haha I guess it's something we don't have yet, will try to add that soon!

**Comment by kcotias** [comment]
Closing this issue since it has been added by you! thankssssss!

**Comment by kcotias** [comment]
Closing this issue since it has been solved by you! Thanks for your contribution!
